# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddBlacklistEntry():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addBlacklistEntry(self):
        self.driver.get("http://localhost:4201/")
        self.driver.set_window_size(1319, 803)
        self.driver.find_element(By.CSS_SELECTOR, "testMenuToggle").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mat-list-item:nth-child(12) > .mat-list-item-content").click()
        self.driver.find_element(By.CSS_SELECTOR, ".testAddObjectBtn").click()
        self.driver.find_element(By.ID, "testNameBLInput").send_keys("Тест Тест Тест")
        self.driver.find_element(By.ID, "testPassportBLInput").send_keys("5700 236543")
        self.driver.find_element(By.ID, "testCommentBLInput").send_keys("Тестовая запись")
        self.driver.find_element(By.CSS_SELECTOR, "testSaveObjectBtn").click()

